### ISSUE TITLE
The build fails with Java 8

### ISSUE THREAD

**Issue by nandana** [ldp4j/eswc2015-tutorial#2]
If the tutorial is not to be used with Java 8, may be it has to mentioned in the README to avoid users running into problems when they use Java 8.

Environment: 
Maven version: Apache Maven 3.3.3
Java version: 1.8.0_05, vendor: Oracle Corporation
OS name: "linux", version: "3.19.0-15-generic", arch: "amd64", family: "unix"

Error log is attached.
http://pastebin.com/pSz3spFS

**Comment by mestebangutierrez** [comment]
Updated the tutorial page to reflect the proper software versions required both for Java (1.7) and Maven (3.2.3+)

**Comment by mestebangutierrez** [comment]
Updated "Presentation" slide to also reflect the proper software versions required for running the tutorial.
