### ISSUE TITLE
Update LDP4j version in pom.xml

### ISSUE THREAD

**Issue by berezovskyi** [ldp4j/eswc2015-tutorial#5]
[ldp4j/ldp4j](https://github.com/ldp4j/ldp4j/releases) is now v0.2.0 and the tutorial should drop `0.2.0-SNAPSHOT` version in favor of `0.2.0`.

I will submit a PR with this change.

**Comment by mestebangutierrez** [comment]
In fact the latest changes are now availble in version 0.3.0-SNAPSHOT (see ldp4j/ldp4j#19 and ldp4j/ldp4j#22).
